CREATE TABLE books (
  ISBN INTEGER PRIMARY KEY,
  title TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE authors (
	ID INTEGER PRIMARY KEY autoincrement,
	name TEXT,

	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE booksForAuthor (
	bookISBN INTEGER,
	authorID INTEGER,

	FOREIGN KEY(bookISBN) REFERENCES books(ISBN) ON DELETE CASCADE,
	FOREIGN KEY(authorID) REFERENCES authors(ID) ON DELETE CASCADE
);

CREATE TABLE bookCount (
	bookISBN INTEGER,
	count INTEGER,

	FOREIGN KEY(bookISBN) REFERENCES books(ISBN) ON DELETE CASCADE
);